### ISSUE TITLE
Cards Trasparent on text

### ISSUE THREAD

**Issue by gbennets** [flowdee/hearthstone-cards#47]
Hello I have a little problem...
The card images can't go on the text and looks trasparent. It's possible to solve that problem?
Thanks a lot for your work, you are a genious :)
![hsimagesovrapposte](https://cloud.githubusercontent.com/assets/19418907/15343351/4b113884-1c9c-11e6-8d3a-c28fced110ce.jpg)

**Comment by gbennets** [comment]
I solve this problem putting in the css:    
 .active {
   z-index: 10;
}

**Comment by flowdee** [comment]
Glad you solved it! 👍
